version: 2
jobs:
  build:
    docker:
      - image: circleci/node:16-browsers
    working_directory: ~/twilio-video-react-app

    steps:
      - checkout

      - restore_cache:
          keys:
            - v1-deps-{{ .Branch }}-{{ checksum "package-lock.json" }}
            - v1-deps-{{ .Branch }}
            - v1-deps

      - run: npm ci

      - save_cache:
          key: v1-deps-{{ .Branch }}-{{ checksum "package-lock.json" }}
          # cache NPM modules and the folder with the Cypress binary
          paths:
            - ~/.npm
            - ~/.cache

      - run:
          name: 'Check server types'
          command: npm run typescript:server

      - run:
          name: 'Build app without auth'
          command: |
            echo REACT_APP_FIREBASE_API_KEY=$REACT_APP_FIREBASE_API_KEY >> .env
            echo REACT_APP_FIREBASE_AUTH_DOMAIN=$REACT_APP_FIREBASE_AUTH_DOMAIN >> .env
            echo REACT_APP_FIREBASE_DATABASE_URL=$REACT_APP_FIREBASE_DATABASE_URL >> .env
            echo REACT_APP_FIREBASE_STORAGE_BUCKET=$REACT_APP_FIREBASE_STORAGE_BUCKET >> .env
            echo REACT_APP_FIREBASE_MESSAGING_SENDER_ID=$REACT_APP_FIREBASE_MESSAGING_SENDER_ID >> .env
            echo REACT_APP_GIT_TAG=$CIRCLE_TAG >> .env
            echo REACT_APP_GIT_COMMIT=$CIRCLE_SHA1 >> .env
            CI=false npm run build

      - persist_to_workspace:
          root: .
          paths:
            - .

  deploy:
    docker:
      - image: google/cloud-sdk
    working_directory: ~/twilio-video-react-app

    steps:
      - attach_workspace:
          at: ~/twilio-video-react-app

      - run: |
          echo $GCLOUD_SERVICE_KEY | gcloud auth activate-service-account --key-file=-
          gcloud --quiet config set project ${GOOGLE_PROJECT_ID}

      - run: echo $CIRCLE_TAG > build/version.txt

      - run: gcloud app deploy -q

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
